### ISSUE TITLE
Test Pilot progress bar

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-l10n/webstatus#110]
Just noticed that the Test Pilot project has a fully green progress bar, even though it’s 43% complete: https://l10n.mozilla-community.org/webdashboard/?locale=fr

Looks like it’s missing the “missing strings” info, not sure if it’s known or not

**Comment by flodolo** [comment]
Yesterday I pushed a fix to cover also the .properties file in the repo, apparently I missed something :-\

**Comment by flodolo** [comment]
Ah, I don't think it's a problem with webstatus (graph is correct there), it's the webdashboard that doesn't know about l20n files.

**Comment by flodolo** [comment]
Fixed by https://github.com/mozilla-l10n/webdashboard/pull/147/
